export const ALL_COURSES_REQUEST = "ALL_COURSES_REQUEST"
export const ALL_COURSES_SUCCESS = "ALL_COURSES_SUCCESS"
export const ALL_COURSES_FAILURE = "ALL_COURSES_FAILURE"
export const COURSE_DETAILS_REQUEST = "COURSE_DETAILS_REQUEST"
export const COURSE_DETAILS_SUCCESS = "COURSE_DETAILS_SUCCESS"
export const COURSE_DETAILS_FAILURE = "COURSE_DETAILS_FAILURE"


export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST"
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS"
export const ALL_USERS_FAILURE = "ALL_USERS_FAILURE"
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAILURE = "USER_DETAILS_FAILURE"
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAILD = "DELETE_USER_FAILD"

/*  Leave Constants */
export const POST_LEAVE_REQUEST = 'POST_LEAVE_REQUEST';
export const POST_LEAVE_SUCCESS = 'POST_LEAVE_SUCCESS';
export const POST_LEAVE_FAILURE = 'POST_LEAVE_FAILURE';
export const FETCH_LEAVES_REQUEST = 'FETCH_LEAVES_REQUEST';
export const FETCH_LEAVES_SUCCESS = 'FETCH_LEAVES_SUCCESS';
export const FETCH_LEAVES_FAILURE = 'FETCH_LEAVES_FAILURE';
export const FETCH_LEAVES_STUDENT_REQUEST = 'FETCH_LEAVES_STUDENT';
export const FETCH_LEAVES_STUDENT_SUCCESS = 'FETCH_LEAVES_SUCCESS';
export const FETCH_LEAVES_STUDENT_FAILURE = 'FETCH_LEAVES_FAILURE';

export const SEND_NOTIFICATION = 'SEND_NOTIFICATION';

/*       Students Constants  */
export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE';


/*       Teachers Constants  */
export const FETCH_TEACHERS_REQUEST = 'FETCH_TEACHERS_REQUEST';
export const FETCH_TEACHERS_SUCCESS = 'FETCH_TEACHERS_SUCCESS';
export const FETCH_TEACHERS_FAILURE = 'FETCH_TEACHERS_FAILURE';


/*       Feaculty  Constants  */
export const FETCH_FEACULTY_REQUEST = 'FETCH_FEACULTY_REQUEST';
export const FETCH_FEACULTY_SUCCESS = 'FETCH_FEACULTY_SUCCESS';
export const FETCH_FEACULTY_FAILURE = 'FETCH_FEACULTY_FAILURE';

/*   Events Constants  */
export const ADD_EVENT_REQUEST = "ADD_EVENT_REQUEST"
export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS"
export const ADD_EVENT_FAILURE = "ADD_EVENT_FAILURE"
export const EVENT_DETAILS = "EVENT_DETAILS"
export const EVENT_SUCCESS = "EVENT_SUCCESS"
export const EVENT_FAILURE = "EVENT_FAILURE"
export const FETCH_EVENTS_REQUEST = "FETCH_EVENTS_REQUEST"
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS"
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE"
export const FETCH_COMING_EVENTS_REQUEST = "FETCH_COMING_EVENTS_REQUEST"
export const FETCH_COMING_EVENTS_FAILURE = "FETCH_COMING_EVENTS_FAILURE"
export const FETCH_COMING_EVENTS_SUCCESS = "FETCH_COMING_EVENTS_SUCCESS"
export const EVENTS_LOADED = "EVENTS_LOADED"

export const SIGNUP_STUDENT_REQUEST = "SIGNUP_STUDENT_REQUEST"
export const SIGNUP_STUDENT_SUCCESS = "SIGNUP_STUDENT_SUCCESS"
export const SIGNUP_STUDENT_FAILURE = "SIGNUP_STUDENT_FAILURE"
export const CLEAR_ERRORS = "CLEAR_ERRORS"